### ISSUE TITLE
Error in Add Amenity, When a new input is created the previous input would double

### ISSUE THREAD

**Issue by braiee** [BeepBoopBit/CondoManagementSystem#1]
Error in Add Amenity, When a new input is created the previous input would double. And there would also be an empty space in the top part for the first input.

To Reproduce Steps to reproduce the behavior:
Go to 'Add Amenity GUI'
Add an amenity and after that add another one again
See error (the previous input doubles)

The previous input should not be doubled 
![Errors in the Add Amenity, When a new input is made the previous input will be doubled](https://user-images.githubusercontent.com/99312804/179890401-a42d59fd-5545-482a-9e44-f37698de075a.JPG)

**Comment by BeepBoopBit** [comment]
Resolve on #10
