### ISSUE TITLE
UPDATED: Button Malfunction in the Edit Description Window and Description Window after interaction with Edit Details Window

### ISSUE THREAD

**Issue by braiee** [BeepBoopBit/CondoManagementSystem#17]
**Describe the bug**
The Edit Description Button for Description Window, And the Confirm Button for Edit Description Window works. But after adding and removing datas in the Edit Details Window. These buttons would not work. It would only work again after restarting the program itself.

BUT WHEN YOU CLICK THE EXIT BUTTONS, IT WOULD STILL UPDATE THE DATAS YOU CHANGED AND ADDED. BUT AFTER RESTARTING THE PROGRAM IT WOULD BE REMOVED. 

![In the Edit Description Window, After Adding Details the Confirm Button does not Work](https://user-images.githubusercontent.com/99312804/180586322-9f3d499e-a83c-45d8-ab01-61ac8a29681c.JPG)
![Does not Work also in the Description Window](https://user-images.githubusercontent.com/99312804/180586324-89fc17d1-fb67-4b59-a3be-fa1efdef2140.JPG)

**Reproduce the bug**
Try to Add and Remove in the Amenities and Details
Confirm it and After that the buttons would not work.

**Expected behavior**
The Buttons should still work even after adding and removing datas in the amenities and details window.

**Comment by BeepBoopBit** [comment]
Resolve in 398e3fcd89e0225013cc02cc95e524c3a9b16375
