### ISSUE TITLE
UPDATED: Mode of Payment in Description Window is different on what you stated on the Sell Condo Window

### ISSUE THREAD

**Issue by braiee** [BeepBoopBit/CondoManagementSystem#18]
**Describe the bug**
Selling the Condo Unit properly works. It modifies the table and say that its already sold. But there are problems with the Mode of Payment. If full payment was stated in the Sell Condo Window, it would not update the mode of payment in the Description Window and would still show Installment.

In testing the Bug Again, I learned that if you put Full Payment in the Sell Condo Window in the Description it would put Installment. And when you put Installment in the Sell Condo Window it would put Full Payment in the Description
"Baliktad" 

![new1](https://user-images.githubusercontent.com/99312804/180586732-7f309b09-35a5-4f35-b115-a4d0f4cd33cb.JPG)
![new2](https://user-images.githubusercontent.com/99312804/180586733-d081c25e-d2dd-4837-9691-c7a5d10dcb5d.JPG)

**Reproduce the bug**
Try to Sell a Condo unit from any floors.
Set the Payment Options to Full Payment and Confirm
See the Description of that Unit. The Mode of Payment is still the same

**Expected behavior**
The Mode of Payment should be updated based on the Payment Options that was stated in the Sell Condo Window

**Comment by BeepBoopBit** [comment]
Resolve at #22
