### ISSUE TITLE
If the registered username or password has an integer, the login would not let it pass 

### ISSUE THREAD

**Issue by braiee** [BeepBoopBit/CondoManagementSystem#2]
If the registered username or password has an integer, the login would not let it pass.

To Reproduce Steps to reproduce the behavior:
Go to 'Register and have a username or password that has an integer'
Click on Register and try to login the account 
See error (the login would not let it pass)

It should accept the username and password that the user entered
![If username has an integer, the login would not work](https://user-images.githubusercontent.com/99312804/179912882-707f0d56-363c-4bcc-8858-e06b2cf07a31.JPG)

**Comment by BeepBoopBit** [comment]
Resolve on #10
