### ISSUE TITLE
Button Malfunction in Edit Description Window After Changing the Datas

### ISSUE THREAD

**Issue by braiee** [BeepBoopBit/CondoManagementSystem#20]
**Describe the bug**
There is a button malfunction in the Edit Description Window After Changing the Datas in the Edit Description Window. Confirm Button would not work.
![Button Malfunction in Edit Description Window After Changing the Datas](https://user-images.githubusercontent.com/99312804/180611638-79eb804e-f1e9-4f8b-b8ec-14720d18cfae.JPG)

**Reproduce the bug**
Try to Change the Value in the Edit Description Window
See that the Confirm button, it would not work. 

**Expected behavior**
The Confirm button should work even after Updating the Details

**Comment by BeepBoopBit** [comment]
Resolve at 398e3fcd89e0225013cc02cc95e524c3a9b16375
