### ISSUE TITLE
In the description window there is an unnecessary label 'Image' and the edit description button is not working

### ISSUE THREAD

**Issue by braiee** [BeepBoopBit/CondoManagementSystem#3]
In the description window there is an unnecessary label 'Image' and the edit description button is not working

To Reproduce Steps to reproduce the behavior:
Go to the Description window and there you'll see the unnecessary label
Click on Edit Description and it would not work
See error 

The label should be removed and the button should call the edit description window
![In the Description Window there is an unnecessary label](https://user-images.githubusercontent.com/99312804/179913447-46d4c803-469a-45a4-ab27-ec06ac5aa1bd.JPG)
![In the Description Window the edit description button is not working](https://user-images.githubusercontent.com/99312804/179913454-1c578db2-2dd6-474b-aa9e-28d8ea18e667.JPG)

**Comment by BeepBoopBit** [comment]
Resolve on #10
