### ISSUE TITLE
Generate report button, search button, and exit button in CMS window doesn't work

### ISSUE THREAD

**Issue by paulreonal** [BeepBoopBit/CondoManagementSystem#4]
Generate report button, search button, and exit button in CMS window doesn't do anything when clicked.

Tried to input the name of a unit in the search bar, but it also doesn't work. Same thing goes if the unit number is searched.

Steps for trying search:
1. Click Floor 3 tab
2. Type 'Ensemble Corinthian Executive Regency' in the search bar
3. Click search

Expected outcome:
Room 303 should show only show up in the tab or appear on the top of the list. 

![image](https://user-images.githubusercontent.com/83939707/179912931-d5bd3c3f-ee17-4b3d-85c6-3b9680b1fd48.png)

**Comment by BeepBoopBit** [comment]
We don't support this kind of feature. The search functionality can only search the values you see on those table. If **Ensemble Corinthian Executive Regency** was in **Room 303 Floor 3** then what you should search for is **303** while inside the the **Floor 3** tab
