### ISSUE TITLE
Description button only shows details of one unit and the 'Edit Description' does not work

### ISSUE THREAD

**Issue by paulreonal** [BeepBoopBit/CondoManagementSystem#5]
Description button only shows details of one unit, The unit details can be seen in the image attached below. In the Description window, the 'Edit Description' does not work when clicked.

Steps:
1. Select a unit without the name 'BigBlue Corinthian Executive Regency'
2. Click the Description button
3. The details show a unit with the details in the image below.
4. Click 'Edit Description' but no window shows up

Expected output:
Should show the details of the selected unit and can be edited.

![image](https://user-images.githubusercontent.com/83939707/179914044-45ace001-5eab-428f-9308-49e7bee79939.png)

**Comment by BeepBoopBit** [comment]
Resolve on #10
