### ISSUE TITLE
Edit Condo Unit and Edit Description is the same

### ISSUE THREAD

**Issue by braiee** [BeepBoopBit/CondoManagementSystem#6]
The Edit Condo Unit Button is the same as the Edit Description Button. There functions are the same and their windows are the same. 

To Reproduce Steps to reproduce the behavior:
Go to the Edit Condo Unit Button and Compare it to the GUI of Edit Description
See that it has the same window and function

The two should have different functions, if not then one of them should be removed.
![Edit condo unit button and desciprion button is the same](https://user-images.githubusercontent.com/99312804/179915030-ddd3c585-7779-4a6a-8385-499e86107fbb.JPG)
![Edit descriptioon](https://user-images.githubusercontent.com/99312804/179915145-fe46a8a5-9957-4021-acef-b736d451ddbc.JPG)

**Comment by BeepBoopBit** [comment]
Resolve on #10
